# Generated by Django 4.2.27 on 2026-01-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.CharField(help_text='Slug-style identifier, e.g., "classic-ats"', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the template style and use case')),
                ('thumbnail_url', models.URLField(blank=True, help_text='URL to template preview image')),
                ('latex_file', models.CharField(help_text='Path to the LaTeX template file relative to TEMPLATES_DIR', max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the template is available for selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'templates',
                'ordering': ['name'],
            },
        ),
    ]
