# Generated by Django 4.2.27 on 2026-01-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_template_latex_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.CharField(help_text='Slug-style identifier, e.g., "altacv"', max_length=100, primary_key=True, serialize=False),
        ),
    ]
