# Generated by Django 4.2.27 on 2026-01-25 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('text', models.TextField(help_text='Raw text of the job description', max_length=20000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_descriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeGenerationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('template_id', models.CharField(help_text='ID of the selected template', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('generated_latex', models.TextField(blank=True, help_text='AI-generated LaTeX source code', null=True)),
                ('generated_pdf_path', models.CharField(blank=True, help_text='Path to the compiled PDF file', max_length=1024, null=True)),
                ('modifications', models.JSONField(blank=True, default=list, help_text='List of human-readable modification summaries made by AI')),
                ('profile_snapshot', models.JSONField(blank=True, default=dict, help_text='Copy of profile data used for generation')),
                ('failure_reason_code', models.CharField(blank=True, db_index=True, help_text='Machine-readable error code', max_length=50, null=True)),
                ('failure_details', models.TextField(blank=True, help_text='Human-readable error details', null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Client-provided idempotency key to prevent duplicate requests', max_length=64, null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed (success or failure)', null=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_requests', to='resumes.jobdescription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resume_generation_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='resume_gene_user_id_ac8b88_idx'), models.Index(fields=['status'], name='resume_gene_status_12309e_idx'), models.Index(fields=['expires_at'], name='resume_gene_expires_bb7415_idx'), models.Index(fields=['idempotency_key'], name='resume_gene_idempot_975784_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['user'], name='job_descrip_user_id_006931_idx'),
        ),
        migrations.AddIndex(
            model_name='jobdescription',
            index=models.Index(fields=['expires_at'], name='job_descrip_expires_48e056_idx'),
        ),
    ]
