# Generated by Django 4.2.27 on 2026-01-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='password_re_token_060a1f_idx',
            old_name='password_re_token_71f3e5_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='password_re_expires_8e96b7_idx',
            old_name='password_re_expires_8c7b1d_idx',
        ),
    ]
